### ISSUE TITLE
Request: Option to exclude Maps as well

### ISSUE THREAD

**Issue by robertl87** [berrnd/contain-google-minus-youtube-and-searchpages#1]
For Maps also counts that it's fine to use it without login.

**Comment by berrnd** [comment]
Sorry, I don't maintain and personally use this anymore...

For me a combination of Containerise and Temporary Containers fit for all my needs...

https://github.com/kintesh/containerise

https://github.com/stoically/temporary-containers

**Comment by robertl87** [comment]
Thanks!
